#????????? ??????????? ??? ?????????? ????????? ????????, ???????? ????? ???????? false.
#spring.thymeleaf.cache=false

# h2  jdbc:h2:mem:tacocloud
#spring.datasource.generate-unique-name=false
#spring.datasource.name=tacocloud
#yaml
spring:
  datasource:
    generate-unique-name: false
    name: tacocloud

# Для куки «JSESSIONID» не установлено корректное значение атрибута «SameSite». Вскоре куки без атрибута «SameSite» или с некорректным значением этого атрибута будут рассматриваться как «Lax». Это означает, что куки больше не будут отправляться в сторонних контекстах. Если ваше приложение зависит от доступности этих кук в подобных контекстах, добавьте к ним атрибут «SameSite=None». Чтобы узнать больше об атрибуте «SameSite», прочитайте https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
# SameSite: None
